# Uncomment this line to define a global platform for your project
# source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'


target 'Dodo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dodo
  pod 'SCLAlertView'
  pod 'Alamofire', '~> 3.4'
  pod 'ChameleonFramework/Swift'
  pod 'Eureka', '~> 1.7'
  pod 'Cosmos', '~> 1.2'
  pod 'FoldingCell'
  pod 'XLPagerTabStrip', '~> 5.0'
  pod 'RxCocoa'
  pod 'NSObject+Rx'
  pod 'Action'
  pod 'Moya/RxSwift'
  pod 'Locksmith'
  pod 'SwiftyJSON'
  pod 'AlamofireImage', '~> 2.0'
  pod 'Reachability', :git => 'https://github.com/ashfurrow/Reachability.git', :branch => 'frameworks'

  target 'DodoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DodoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
